### ISSUE TITLE
[讨论]关于链接收集的问题

### ISSUE THREAD

**Issue by basecss** [fenbility/daily-welfare#15]
早上整理了一下 2015 年 1 月份的链接。有一些问题：

大概是 2014 年 11 月份水群发起了 @toosolo 自动收集链接。起初 12 月份的效果很不错，规则不多。遵循规则的内容才会被收集，整体质量上很不错。尤其是自动整理出来的格式很“入眼”。

到了 1 月份，纷纷提出为 @toosolo 新增更多的“智能”功能。然后关于【每日福利】的收集就乱了。纷纷不按规则出牌，最终如预料，这一期的质量显然没有以往高。

这不是水群发起 #每日福利# 这个活动的初衷啊。

**Comment by Keystion** [comment]
是不是可以适当的约束一下下，最起码每个连接添加一个或者关键词。

**Comment by TooBug** [comment]
改下规则？@福利的才记录？

**Comment by basecss** [comment]
```
新纪录：#每日福利#   /* 遵循原来的规则 */
已有的不记录： @xxx 刚才的福利已存在，只反馈当月的的 [当月纪录不重复]
```

以上纯属个人 YY。

我觉的约束一下就好，不然一大堆链接没几个正常的就越办越杂了。另外这里质量搞好一点，也是为了后期某个 10 年长跑项目打基础嘛。。。@TooBug

**Comment by TooBug** [comment]
已修改，人工记录。
