### ISSUE TITLE
关于数据日益增多问题

### ISSUE THREAD

**Issue by Keystion** [fenbility/daily-welfare#17]
由于数据越来越多，是否考虑增加一个站点来提供`访问`、`搜索`；

**Comment by TooBug** [comment]
coming soon~


原始邮件
发件人:Keystionnotifications@github.com
收件人:fenbility/daily-welfaredaily-welfare@noreply.github.com
发送时间:2015年8月11日(周二) 18:13
主题:[daily-welfare] 关于数据日益增多问题 (#17)


由于数据越来越多，是否考虑增加一个站点来提供访问、搜索；

**Comment by Keystion** [comment]
原来八哥已经默默的开发出来了。👍 [前端百科 - 分享列表](http://f2er.info/collection)

**Comment by TooBug** [comment]
@Keystion 嘿嘿，还不完善，所以没宣传。有个小书签，有兴趣的话可以玩玩。在chrome中新建一个书签，地址写下面这一段，以后看到要推荐的东西直接点这个书签就好了，选中的文字会作为摘要。

```javascript
javascript:~(function(){var baseUrl = 'http://f2er.info/collection?';var summary = document.getSelection().toString().replace(/\n/g,'');if(!summary){summary = prompt('%E8%AF%B7%E5%A1%AB%E5%86%99%E6%91%98%E8%A6%81(%E4%B9%9F%E5%8F%AF%E4%BB%A5%E7%A8%8D%E5%90%8E%E5%9C%A8%E9%A1%B5%E9%9D%A2%E5%A1%AB%E5%86%99)');}var url = baseUrl + 'url=' + encodeURIComponent(location.href) +'&title=' + encodeURIComponent(document.title) + '&summary=' + encodeURIComponent(summary);window.open(url);})();
```

**Comment by Keystion** [comment]
@TooBug 用了一下，很棒！
